solutionTemplateName: testapp2-config-temp
solutionTemplateId: /subscriptions/d1e52cbc-b073-42e2-a0a0-c2f547118a6e/resourceGroups/jn-ghawf-euap/providers/Microsoft.Edge/solutionTemplates/testapp2-config-temp
versions:
  - version: 3.3.7
    solutionTemplateVersionId: /subscriptions/d1e52cbc-b073-42e2-a0a0-c2f547118a6e/resourceGroups/jn-ghawf-euap/providers/Microsoft.Edge/solutionTemplates/testapp2-config-temp/versions/3.3.7
    revisions: []
  - version: 3.3.8
    solutionTemplateVersionId: /subscriptions/d1e52cbc-b073-42e2-a0a0-c2f547118a6e/resourceGroups/jn-ghawf-euap/providers/Microsoft.Edge/solutionTemplates/testapp2-config-temp/versions/3.3.8
    revisions: []
  - version: 3.3.9
    solutionTemplateVersionId: /subscriptions/d1e52cbc-b073-42e2-a0a0-c2f547118a6e/resourceGroups/jn-ghawf-euap/providers/Microsoft.Edge/solutionTemplates/testapp2-config-temp/versions/3.3.9
    revisions: []
