name: 'WO Azure Setup'
description: 'Log in to Azure using OIDC, install cli and setup endpoint'
inputs:
  client-id:
    required: true
    description: 'Azure Client ID'
  tenant-id:
    required: true
    description: 'Azure Tenant ID'
  subscription-id:
    required: true
    description: 'Azure Subscription ID'
  azcliversion:
    required: true
runs:
  using: "composite"
  steps:
    - name: Azure Login with OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}

    - name: Install Azure CLI
      uses: azure/cli@v2
      with:
        #azcliversion: ${{ inputs.azcliversion }}
        azcliversion: "2.73.0"
        inlineScript: |
          echo "az cli setup with latest version"
          az cloud update --endpoint-resource-manager "https://management.azure.com"

    - name: Install prerequite extensions
      id: wo-prereqs
      uses: ./.github/actions/wo-prereqs
