solutionTemplateName: testapp3-config-temp
solutionTemplateId: /subscriptions/d1e52cbc-b073-42e2-a0a0-c2f547118a6e/resourceGroups/jn-ghawf-euap/providers/Microsoft.Edge/solutionTemplates/testapp3-config-temp
versions:
  - version: 1.0.0
    solutionTemplateVersionId: /subscriptions/d1e52cbc-b073-42e2-a0a0-c2f547118a6e/resourceGroups/jn-ghawf-euap/providers/Microsoft.Edge/solutionTemplates/testapp3-config-temp/versions/1.0.0
    revisions: []
