name: Delete AKS connected cluster 
description: Delete AKS cluster
inputs:
  site:
    description: site used for AKS cluster
    required: true
  rg:
    description: RG to be used for AKS cluster
    required: true

runs:
  using: "composite"
  steps:
    - name: source site info
      id: siteinfo
      uses: ./.github/actions/wo-get-site-info
      with:
        site: ${{ inputs.site }}
        rg: ${{ inputs.rg }}

    - name: check if cluster exists
      id: deletecluster
      shell: bash
      run: |
        echo
        echo "Delete cluster: ${{ steps.siteinfo.outputs.siteClsName }} site: ${{ inputs.site }} rg: ${{ steps.siteinfo.outputs.rg }}"

        aksName=$(az aks show --resource-group "${{ steps.siteinfo.outputs.rg }}" --name "${{ steps.siteinfo.outputs.siteClsName }}" --subscription "${{ steps.siteinfo.outputs.subId }}" --query name -o tsv 2>&1) || true

        if [[ "$aksName" == "${{ steps.siteinfo.outputs.siteClsName }}" ]]; then

          echo "Delete cluster"
          az connectedk8s delete --resource-group "${{ steps.siteinfo.outputs.rg }}" --name "${{ steps.siteinfo.outputs.siteClsName }}" -y
          az aks delete --resource-group "${{ steps.siteinfo.outputs.rg }}" --name "${{ steps.siteinfo.outputs.siteClsName }}" -y

          echo "Delete cluster-identity"
          az identity delete --resource-group "${{ steps.siteinfo.outputs.rg }}" --name "${{ steps.siteinfo.outputs.siteClsId }}"
        fi
