metadata:
  name: common-config-template
  version: 1.0.0
schema:
  name: common-schema
  version: 1.0.0
configs:
  SqlServerEndpoint: http://localhost/SqlServerEndpoint
  LineHealthEndpoint: http://localhost/LineHealthEndpoint
